name: GitHub Actions Checks

on:
  push:
    paths:
      - '.github/**'

jobs:
  gha-checks:
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: mu88/common/.github/workflows/gha-checks.yml@3ea4b09ec497e29a984c24e70d99b9baebdeeb8f # main
